opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
disabled_rules:
  - force_try
  - notification_center_detachment
file_length:
  warning: 500
  error: 700
line_length:
  warning: 140
type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ui
    - cg
    - id